### ISSUE TITLE
JS2 issues 

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerMorphoDepot#3]
This is from JS2 instance:

```
exouser@instance-55:/media/volume/MyData$ gh auth status
github.com
  ✓ Logged in to github.com as muratmaga (/home/exouser/.config/gh/hosts.yml)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
  
exouser@instance-55:/media/volume/MyData$ vglrun -d egl ~/Slicer/Slicer 
libpng warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
libpng warning: iCCP: known incorrect sRGB profile
Switch to module:  "Welcome"
Switch to module:  "MorphoDepot"
('unknown command "search" for "gh"\n\nUsage:  gh <command> <subcommand> [flags]\n\nAvailable commands:\n  actions\n  alias\n  api\n  auth\n  browse\n  codespace\n  completion\n  config\n  extension\n  gist\n  gpg-key\n  help\n  issue\n  pr\n  release\n  repo\n  run\n  secret\n  ssh-key\n  workflow\n\n', None)
Traceback (most recent call last):
  File "/media/volume/MyData/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 152, in updateIssueList
    issueList = self.logic.issueList()
  File "/media/volume/MyData/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 255, in issueList
    issueList = json.loads(self.gh("search issues --assignee=@me --state open --json repository,title,number"))
  File "/home/exouser/Slicer/lib/Python/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/exouser/Slicer/lib/Python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/exouser/Slicer/lib/Python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by pieper** [comment]
Which version do you have and how did you install it?  I have this:
```
$ gh --version
gh version 2.55.0 (2024-08-20)
https://github.com/cli/cli/releases/tag/v2.55.0
$ which gh
/usr/bin/gh
```

The search command should be valid: https://cli.github.com/manual/gh_search_issues

**Comment by muratmaga** [comment]
I did 'sudo apt install gh'.
```
exouser@instance-55:/$ gh --version
gh version 2.4.0+dfsg1 (2022-03-23 Ubuntu 2.4.0+dfsg1-2)
https://github.com/cli/cli/releases/latest
exouser@instance-55:/$ which gh
/usr/bin/gh
```

**Comment by muratmaga** [comment]
I hve upgraded to 2.58 from the CLI github instruction. I no longer have this problem. When make a new segmentation and then hit save and request reivew, I am still getting the Not found page, along with these errors in Slicer
```
Switch to module:  "MorphoDepot"
issueRequestReview
issueCheckpoint
Popen(['git', 'cat-file', '--batch-check'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=False, shell=None, istream=<valid stream>)
Popen(['git', 'cat-file', '--batch'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=False, shell=None, istream=<valid stream>)
Popen(['git', 'push', '--porcelain', '--', 'origin', 'issue-7'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=True, shell=None, istream=None)
AutoInterrupt wait stderr: b"error: failed to push some refs to 'https://github.com/muratmaga/MD_E15.git'"
Error lines received while fetching: error: failed to push some refs to 'https://github.com/muratmaga/MD_E15.git'
```

**Comment by muratmaga** [comment]
Is it normal it is trying to push to my account as opposed to a branch in your?

**Comment by muratmaga** [comment]
So the problem is, this is pushing to my account, but there is no issue #7 on my repo, hence the not found error. Is this the way it is supposed to work, or is there some sort of misconfiguration on my end.

**Comment by pieper** [comment]
About the issue/branch yes, it should be using your account, as configured in gh, to store a fork of my repo.  The issues are in my repo, and branches in your repo are named `issue-#` where the number is the one from my repo.  You don't need an issue-7, because you are just pushing a branch named issue-7.  Also the seg files are `issue-#.seg.nrrd` so they can all be easily merged into the PI repo with no conflicts.  If the PI wants to copy the segments into a combined segmentation they can do that later.

Other than logging into gh there shouldn't be any other configuration on your end. 

Not sure why it's not pushing to your repo though.  Are you doing this on a JS2 instance I can look at tomorrow or we can do a quick call?

**Comment by muratmaga** [comment]
I also started from the scratch, and the issue is still there for me at the push level. 
Same URL not found page on the web browser, same error messages in the console. 

```
issueRequestReview
issueCheckpoint
Popen(['git', 'cat-file', '--batch-check'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=False, shell=None, istream=<valid stream>)
Popen(['git', 'cat-file', '--batch'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=False, shell=None, istream=<valid stream>)
Popen(['git', 'push', '--porcelain', '--', 'origin', 'issue-7'], cwd=/home/exouser/Documents/MD_E15, universal_newlines=True, shell=None, istream=None)
AutoInterrupt wait stderr: b"error: failed to push some refs to 'https://github.com/muratmaga/MD_E15.git'"
Error lines received while fetching: error: failed to push some refs to 'https://github.com/muratmaga/MD_E15.git'
```

**Comment by muratmaga** [comment]
I checked your instance, everything appears the same way as my instance. The only difference I can see you have overwritten an existing segment, whereas I created an additional one. I can' see how that would have made a difference.

**Comment by muratmaga** [comment]
Things worked in our lab computer with ubuntu (though I did not create a segment, but overwrite one of them. I will try to do that on JS too.

**Comment by muratmaga** [comment]
OK. Things seemed to be working with JS2 now. It looks like between when I cloned the repo and start working on it there was a small change. I did a pull origin and things seem working now. I am making some usabiliity comments on the MorphoDepot repo.
