### ISSUE TITLE
Filter the issues to list on MD related ones

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerMorphoDepot#5]
Currently when the refresh button is pressed, the returned issues list contains everything the user is involved with. 

This can have potential consequences (like clicking on wrong issue). We should look into the option filtering the issues only applicable to MorphoDepot repos. This might be topics field, or some other tag we use to identify which repos will be included in the MD meta tree.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/31bd414c-2eb4-4bea-bdbf-81d3743d3676">

**Comment by pieper** [comment]
This is done.  Now only repos with the morphodepot topic are included
